jobs: 100
software-deployment-method:
  - conda
  - apptainer
default-resources: [cpus=1, mem_mb=16000, time_min=120, ncbi_api=0]
resources: [cpus=32, mem_mb=180000, ncbi_api=5]
latency-wait: 120
singularity-args: "--home $HOME:$HOME --bind /geomicro:/geomicro --bind /nfs:/nfs"
rerun-triggers: mtime
