channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bbmap=39.13
  - spades=4.0.0
  - megahit=1.2.9
  - diamond=2.1.10
  - prodigal=2.6.3
  - perl-statistics-basic=1.6611
  - perl-sort-naturally=1.03
  - perl-perlio-gzip=0.20
#  - pip:
#    - git+https://github.com/bioinfomaticsCSU/MEC.git@ca734269c518d48e3a6088063961ccfff15da536